config/routes.rb
NaturesPathReboot::Application.routes.draw do
  resources :menus

  resources :nutrition_infos

  resources :ingredients

  get 'administrator/index'

  get 'users/:id/confirm/:confirmation_code', to: 'users#check_confirm_code', as: 'confirm'

  get 'images/:id/:style', to: 'images#show_style'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users
  resources :password_resets

  resources :home_posts

  resources :pages, except: :show

  match 'recipes/admin_show'
  resources :recipes 
  resources :images

  get ':id', to: 'pages#show', as: :page
  put ':id', to: 'pages#update', as: :page
  root to: 'home_posts#show', id: 1

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :description, :title

  has_one :image, as: :image_reference 
  has_many :recipe_rel_ingredients
  #has_and_belongs_to_many :recipes
  has_many :ingredients, :through => :recipe_rel_ingredients
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  # getters and setters
  attr_accessible :description, :title, :ingredient_ids, :nutrition_info_attributes, :nutrition_info_id, :inventory_items_attributes, :category 

  # relationships
  has_one :nutrition_info
  has_many :inventory_items
  has_and_belongs_to_many :ingredients

  # validations
  # validates_presence_of :size, :category, :title, :on => :create

  # helpers
  accepts_nested_attributes_for :nutrition_info, allow_destroy: true
  accepts_nested_attributes_for :inventory_items, allow_destroy: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :admin_filter
  skip_before_filter :admin_filter, :only => [:show, :index]

  def admin_show
    @recipes = Recipe.all

    respond_to do |format|
      format.html  #admin_show.html.erb
      format.json { render json: @recipes }
    end
  end
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
    @soups = Recipe.where("category = ?", "Soup").all
    @full_meals =Recipe.where("category = ?", "Main Dish").all 
    @sandwiches =Recipe.where("category = ?", "Sandwich").all 
    @cold_dishes =Recipe.where("category = ?", "Cold Dish").all 


    # setup our current_menus
    # -----------------------
    #
    # Used in view layer
    #
    # The way this works currently, a recipe could be displayed
    # both as a salad and an entree

    @current_menus = Menu.where("start_date <= ? AND end_date >= ?", Date.today, Date.today).first
    puts "current_menu: "
    puts @current_menus
    temp_entrees = []
    temp_salads = []

    @menu_entrees = []
    @menu_salads = []

    if @current_menus
      # iterate on recipe_ids
      @current_menus.recipe_ids.each do |recipe_id|
        # use recipe_id to look up recipe
        temp_recipe = Recipe.where("id = ?", recipe_id).first
        # iterate on inventory items of that recipe
        if temp_recipe.category == "Salad"
          temp_salads << temp_recipe
        else
          temp_entrees << temp_recipe
        end
      end
      # save temp values into member scoped arrays
      @menu_entrees = temp_entrees 
      @menu_salads = temp_salads
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @nutrition_info = NutritionInfo.where( "recipe_id = ?", @recipe.id ).first
    @inventory_items = []
    @recipe.inventory_items.each do |inventory_item|
      @inventory_items << inventory_item
    end


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  #def build_nutrition_info
  #@recipe.nutrition_info_attributes = params[:nutrition_infos]
  #end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new
    @recipe.build_nutrition_info

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save 
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div class="np-blue" id="error_explanation">
      <div class="np-blue"><h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

        <ul>
          <% @recipe.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
      <%= f.fields_for :inventory_items do |builder| %>
        <%= render "inventory_item_fields", f: builder %>
      <% end %>
      <%= link_to_add_association "Add Inventory Item", f, :inventory_items %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class = "field">
    <%= f.label :category, "Choose Type" %><br />
    <% ['Salad', 'Main Dish', 'Soup', 'Cold Dish', 'Sandwich'].each do |category| %>
      <%= f.radio_button(:category, category) %> 
      <label><%= category.to_s%></label><br />
    <% end %>
  </div>
  <div class="field">
    <h2> Ingredients (leave blank to exclude from recipe) </h2>
    <%= fields_for :recipe_rel_ingredients do |builder| %>
      <%= render 'recipe_rel_ingredient_fields', f: builder, recipe: @recipe %>
    <% end %>
  </div>
  <div class = "field">
    <%= f.fields_for :nutrition_info do |builder| %>
      <%= render 'nutrition_info_fields', f: builder %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_inventory_item_fields.html.erb
<div class = "nested-fields">
  <fieldset>
    <legend>Inventory Item</legend>
  <div class = "field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class = "field">
    <%= f.label :quantity, "Choose Size" %> <br />
    <% ['Regular', 'Large', 'Family'].each do |quantity| %>
      <%= f.radio_button(:quantity, quantity) %> 
      <label><%=quantity.to_s%></label><br />
    <% end %>
  </div>
  <div class = "field">
    <%= link_to_remove_association "Remove Inventory Item", f %>
  </div>
  </fieldset>
</div>

app/views/recipes/_nutrition_info_fields.html.erb
<fieldset>
  <legend>Nutrition Info</legend>
  <div class="field">
    <%= f.label :calories %><br />
    <%= f.text_field :calories %>
  </div>
  <div class="field">
    <%= f.label :protein %><br />
    <%= f.text_field :protein %>
  </div>
  <div class="field">
    <%= f.label :fat %><br />
    <%= f.text_field :fat %>
  </div>
  <div class="field">
    <%= f.label :carbohydrates %><br />
    <%= f.text_field :carbohydates %>
  </div>
  <div class="field">
    <%= f.label :fiber %><br />
    <%= f.text_field :fiber %>
  </div>
</fieldset>

app/views/recipes/_recipe_rel_ingredient_fields.html.erb
<% Ingredient.all.each do |ingredient| %>
  <%= hidden_field_tag "recipe[ingredient_ids][]", nil%>
  <%= check_box_tag :ingredient_ids, ingredient.id, @recipe.ingredient_ids.include?(ingredient.id), :name => 'recipe[ingredient_ids][]' %>
  <%= label_tag dom_id(ingredient), ingredient.title %>
  <br /> 
<br />
<% end %>

app/views/recipes/admin_show.html.erb
<div id="page-content" class="span-23 np-padding np-red">
<h1>Listing recipes</h1>

<table class="np-blue">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.title %></td>
    <td><%= recipe.description %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_path %>
</div>

app/views/recipes/edit.html.erb
<div id="page-content" class="span-23 np-red np-padding last">
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>
</div>

app/views/recipes/index.html.erb
<div id="page-content" class="span-24">
  <% if @current_menus == nil %>
    <div class="span-11 np-padding np-blue">
      <p class="x-large" style="padding-top: 20px; margin-bottom: 5px;">
      There are no menus available.
      </p>
    </div>
  <% else %>
      <div class="span-11 np-padding np-blue">
        <p class="x-large" style="padding-top: 20px; margin-bottom: 5px;">
        CURRENT WEEK'S MENU
        </p>
        <p class="center">
        Available to order <%= @current_menus.start_date %> through <%= @current_menus.end_date %>
        <br/>
        Avaiable for pick up after 3 PM on <%= @current_menus.pickUpDate%>
        </p>
        <p class="center">
        <% @menu_entrees.each do |menu_entree| %>
          <%= link_to menu_entree.title, recipe_path(menu_entree.id) %>  
          <% menu_entree.inventory_items.each_with_index do |inventory_item, index| %>
            <%= inventory_item.quantity %> - <%= number_with_precision inventory_item.price, :precision => 2 %>
            <% if index != menu_entree.inventory_items.length-1 %>
              <%= "," %>
            <% end %>
          <% end %>
          <br />
        <% end %>
        </p>
        <div class = "x-large" style="text-decoration:underline;">
          Salads
        </div>
        <hr class="space" />
        <div class="large center" >
          <% @menu_salads.each do |menu_salad| %>
            <%= link_to menu_salad.title, recipe_path(menu_salad.id) %><br />  
          <% end %>
          Small (2 cups): $2 <br />
          Large (4 cups): $3.50
        </div>
        <% if admin %>
          <%= link_to 'Edit', edit_menu_path(@current_menus) %></td>
        <% end %>
      </div>
  <% end %>
  <div class="span-11 last np-padding np-blue">
    <p class="x-large"style="padding-top: 20px; margin-bottom: 5px;" >COMPLETE MENU</p>
    <h2 style="text-align:center;">(rotated weekly)</h2>
    <p class="center" style="font-size:15px;">Click on selection for nutrition information and pricing</p>
    <hr class="space" />
    <h2 style="text-align:center;">SOUPS/STEWS</h2>
    <% if @soups.length > 0 %>
      <% @soups.each do |soup| %>
        <p class="center"style="font-size:15px;">
        <%= link_to soup.title, recipe_path(soup.id) %> - 
        <% soup.inventory_items.each_with_index do |inventory_item, index| %>
          $<%= number_with_precision inventory_item.price , :precision => 2%>
          (<%= inventory_item.quantity%>)
          <%= (index == soup.inventory_items.length-1) ? "" : "," %> 
        <% end %>
        </p>
      <% end %>
    <% end %>
    <hr class="space" />
    <h2 style="text-align:center;">MAIN DISHES</h2>
    <% if @full_meals.length > 0 %>
      <% @full_meals.each do |full_meal| %>
        <p class="center" style="font-size:15px;">
        <%= link_to full_meal.title, recipe_path(full_meal.id) %> - 
        <% full_meal.inventory_items.each_with_index do |inventory_item, index| %>
          $<%= number_with_precision inventory_item.price, :precision => 2 %>
          (<%= inventory_item.quantity%>)
          <%= (index == full_meal.inventory_items.length-1) ? "" : "," %> 
        <% end %>
        </p>
      <% end %>
    <% end %>
    <hr class="space" />
    <h2 style="text-align:center;">SANDWICHES</h2>
    <% if @sandwiches.length > 0 %>
      <% @sandwiches.each do |sandwich| %>
        <p class="center" style="font-size:15px;">
        <%= link_to sandwich.title, recipe_path(sandwich.id) %> - 
        <% sandwich.inventory_items.each_with_index do |inventory_item, index| %>
          $<%= number_with_precision inventory_item.price, :precision => 2 %>
          (<%= inventory_item.quantity%>)
          <%= (index == sandwich.inventory_items.length-1) ? "" : "," %> 
        <% end %>
        </p>
      <% end %>
    <% end %>
    <hr class="space" />
    <h2 style="text-align:center;">COLD DISHES</h2>
    <% if @cold_dishes.length > 0 %>
      <% @cold_dishes.each do |cold_dish| %>
        <p class="center" style="font-size:15px;">
        <%= link_to cold_dish.title, recipe_path(cold_dish.id) %> - 
        <% cold_dish.inventory_items.each_with_index do |inventory_item, index| %>
          $<%= number_with_precision inventory_item.price , :precision => 2%>
          (<%= inventory_item.quantity%>)
          <%= (index == cold_dish.inventory_items.length-1) ? "" : "," %> 
        <% end %>
        </p>
      <% end %>
    <% end %>

  </div>
</div>

app/views/recipes/new.html.erb
<hr class="space">
<div id="page-content" class="span-23 np-red np-padding last">
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>
</div>

app/views/recipes/show.html.erb
<div id="page-content" class="span-24 np-blue">
  <p id="notice" class="np-red"><%= notice %></p>

  <div class="center">
    <h1>
      <%= @recipe.title %> - 
      <% if @inventory_items.length > 0 %>
        <% @inventory_items.each do |inventory_item| %>
          $ <%= number_with_precision inventory_item.price, :precision => 2%> 
        <% end %>
      <% end %>
    </h1>
    <h2>
      <%= @recipe.description %>
    </h2>
    <h3>
      Ingredients:
      <% @recipe.ingredient_ids.each_with_index do |ingredient_id, index| %>
        <% result =  Ingredient.find(ingredient_id).title %>
        <% if index != @recipe.ingredient_ids.length-1 %>
          <% result = result << ', ' %>  
        <% end %>
        <%= result %>
      <% end %>
    </h3>
    <hr class="space" />
    <h2>
      Nutrition Facts (Regular Size)
    </h2>
    <div class="span-9">&nbsp;</div>
    <div class="np-white span-6">
      <% if @nutrition_info %>
        <div class="span-6">
          <div class="span-3" style="font-face: arial; padding-left:20px; text-align: left;">
            <b> Calories </b> <br /> 
            Protein (g) <br />
            Fat (g) <br />
            Carbohydrates (g)<br />
            Fiber (g)<br />

          </div>
          <div class="prepend-1 span-1"  style="text-align: center;">
            <b><%= @nutrition_info.calories.to_i %></b>  <br />
            <%= @nutrition_info.protein.to_i %>  <br />
            <%= @nutrition_info.fat.to_i %>  <br />
            <%= @nutrition_info.carbohydates.to_i %> <br />
            <%= @nutrition_info.fiber.to_i %> <br />
          </div>
        </div>
      <% end %>
    </div>
    <hr class="space" />
    <div class="span-24" style="text-align:center;">
      <p>Large sizes are 1.5 times the Regular size.  Family size includes 4 Regular servings.</p>
    </div>
  </div>

  <% if admin %>
    <div class="prepend-10 span-6">
      <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
      <%= link_to 'Back', recipes_path %>
    </div>
  <% end %>
</div>