config/routes.rb
NaturesPathReboot::Application.routes.draw do
  resources :menus

  resources :nutrition_infos

  resources :ingredients

  get 'administrator/index'

  get 'users/:id/confirm/:confirmation_code', to: 'users#check_confirm_code', as: 'confirm'

  get 'images/:id/:style', to: 'images#show_style'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users
  resources :password_resets

  resources :home_posts

  resources :pages, except: :show

  match 'recipes/admin_show'
  resources :recipes 
  resources :images

  get ':id', to: 'pages#show', as: :page
  put ':id', to: 'pages#update', as: :page
  root to: 'home_posts#show', id: 1

end

app/models/home_post.rb
class HomePost < ActiveRecord::Base
  attr_accessible :bottom_body, :bottom_title, :title, :top_body, :top_title
end

app/controllers/home_posts_controller.rb
class HomePostsController < ApplicationController
  before_filter :admin_filter
  skip_before_filter :admin_filter, :only => [:show]
  # GET /home_posts
  # GET /home_posts.json
  def index
    @home_posts = HomePost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @home_posts }
    end
  end

  # GET /home_posts/1
  # GET /home_posts/1.json
  def show
    @home_post = HomePost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home_post }
    end
  end

  # GET /home_posts/new
  # GET /home_posts/new.json
  def new
    @home_post = HomePost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home_post }
    end
  end

  # GET /home_posts/1/edit
  def edit
    @home_post = HomePost.find(params[:id])
  end

  # POST /home_posts
  # POST /home_posts.json
  def create
    @home_post = HomePost.new(params[:home_post])

    respond_to do |format|
      if @home_post.save
        format.html { redirect_to @home_post, notice: 'Home post was successfully created.' }
        format.json { render json: @home_post, status: :created, location: @home_post }
      else
        format.html { render action: "new" }
        format.json { render json: @home_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /home_posts/1
  # PUT /home_posts/1.json
  def update
    @home_post = HomePost.find(params[:id])

    respond_to do |format|
      if @home_post.update_attributes(params[:home_post])
        format.html { redirect_to @home_post, notice: 'Home post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /home_posts/1
  # DELETE /home_posts/1.json
  def destroy
    @home_post = HomePost.find(params[:id])
    @home_post.destroy

    respond_to do |format|
      format.html { redirect_to home_posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/home_posts_helper.rb
module HomePostsHelper
end

app/views/home_posts/_form.html.erb
<%= form_for(@home_post) do |f| %>
  <% if @home_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home_post.errors.count, "error") %> prohibited this home_post from being saved:</h2>

      <ul>
      <% @home_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :top_body %><br />
    <%= f.text_area :top_body %>
  </div>
  <div class="field">
    <%= f.label :bottom_body %><br />
    <%= f.text_area :bottom_body %>
  </div>
  <div class="field">
    <%= f.label :top_title %><br />
    <%= f.text_field :top_title %>
  </div>
  <div class="field">
    <%= f.label :bottom_title %><br />
    <%= f.text_field :bottom_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home_posts/edit.html.erb
<div id="page-content" class="span-24 np-blue np-padding <%= @home_post.title %>">
  <h1>Editing home_post</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @home_post %> |
  <%= link_to 'Back', home_posts_path %>
</div>

app/views/home_posts/index.html.erb
<div id="page-content" class="span-24">
  <h1>Listing home_posts</h1>

  <table>
    <tr>
      <th>Title</th>
      <th>Top body</th>
      <th>Bottom body</th>
      <th>Top title</th>
      <th>Bottom title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @home_posts.each do |home_post| %>
      <tr>
        <td><%= home_post.title %></td>
        <td><%= home_post.top_body %></td>
        <td><%= home_post.bottom_body %></td>
        <td><%= home_post.top_title %></td>
        <td><%= home_post.bottom_title %></td>
        <td><%= link_to 'Show', home_post %></td>
        <td><%= link_to 'Edit', edit_home_post_path(home_post) %></td>
        <td><%= link_to 'Destroy', home_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <br />

  <%= link_to 'New Home post', new_home_post_path %>
</div>

app/views/home_posts/new.html.erb
<div id="page-content" class="span-24">
  <h1>New home_post</h1>

  <%= render 'form' %>

  <%= link_to 'Back', home_posts_path %>
</div>

app/views/home_posts/show.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "home_posts.js" %>
<% end %>

<hr class="space">
<div id="home-post-side" class="home-post-side np-padding span-6 first">
  <h3>Ingredient Close Up</h3>
  <p>Coming soon!</p>
</div>
<div class = "prepend-1 span-16 last">
  <div id="home-post-top" class ="span-15 home-post-top">
    <div class="span-15">
      <p>
      <h2><%= @home_post.top_title %></h2>
      </p>
    </div>

    <div class="span-15">
      <p>
      <%= @home_post.top_body.html_safe %>
      </p>
    </div>
  </div>
  <hr class="space">

  <div id="home-post-bottom" class ="home-post-bottom np-padding">
    <p>
    <h2><%= @home_post.bottom_title %></h2>
    </p>
    <p>
    <%= @home_post.bottom_body.html_safe %>
    </p>
    <% if admin %>
        <%= link_to 'Edit', edit_home_post_path(@home_post) %> |
        <%= link_to 'Back to index of home posts', home_posts_path %>
    <% end %>

  </div>
</div>