config/routes.rb
NaturesPathReboot::Application.routes.draw do
  resources :menus

  resources :nutrition_infos

  resources :ingredients

  get 'administrator/index'

  get 'users/:id/confirm/:confirmation_code', to: 'users#check_confirm_code', as: 'confirm'

  get 'images/:id/:style', to: 'images#show_style'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users
  resources :password_resets

  resources :home_posts

  resources :pages, except: :show

  match 'recipes/admin_show'
  resources :recipes 
  resources :images

  get ':id', to: 'pages#show', as: :page
  put ':id', to: 'pages#update', as: :page
  root to: 'home_posts#show', id: 1

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :description, :title

  has_one :image, as: :image_reference 
  has_many :recipe_rel_ingredients
  #has_and_belongs_to_many :recipes
  has_many :ingredients, :through => :recipe_rel_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :admin_filter
  skip_before_filter :admin_filter, :only => [:show]
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class=field">
    <%= f.fields_for :image_reference do |builder| %>
      <%= render 'image_select', f: builder %>
    <% end %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/_image_select.html.erb
<%= f.label :image_reference, "Image" %>
<%= select("post", "image_reference_id", Image.all.collect {|p| [ p.image_object_file_name, p.id ] }, {:include_blank => 'None'}) %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<div id="page-content" class="span-23 np-padding np-red">
<h1>Listing ingredients</h1>

<table class="np-blue">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.title %></td>
    <td><%= ingredient.description %></td>
    <td><%= link_to 'Show', ingredient %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ingredient', new_ingredient_path %>
</div>

app/views/ingredients/new.html.erb
<div id="page-content" class="span-23 np-padding np-blue">
  <h1>New ingredient</h1>

  <%= render 'form' %>

  <%= link_to 'Back', ingredients_path %>
</div>

app/views/ingredients/show.html.erb
<div id="page-content" class="span-23 np-padding np-blue">
  <p id="notice"><%= notice %></p>

  <p>
  <b>Title:</b>
  <%= @ingredient.title %>
  </p>

  <p>
  <b>Description:</b>
  <%= @ingredient.description.html_safe %>
  </p>


  <%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
  <%= link_to 'Back', ingredients_path %>
</div>