config/routes.rb
NaturesPathReboot::Application.routes.draw do
  resources :menus

  resources :nutrition_infos

  resources :ingredients

  get 'administrator/index'

  get 'users/:id/confirm/:confirmation_code', to: 'users#check_confirm_code', as: 'confirm'

  get 'images/:id/:style', to: 'images#show_style'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users
  resources :password_resets

  resources :home_posts

  resources :pages, except: :show

  match 'recipes/admin_show'
  resources :recipes 
  resources :images

  get ':id', to: 'pages#show', as: :page
  put ':id', to: 'pages#update', as: :page
  root to: 'home_posts#show', id: 1

end

app/models/nutrition_info.rb
class NutritionInfo < ActiveRecord::Base
  attr_accessible :calories, :carbohydates, :fat, :fiber, :protein 

  belongs_to :recipe
end

app/controllers/nutrition_infos_controller.rb
class NutritionInfosController < ApplicationController
  before_filter :admin_filter
  skip_before_filter :admin_filter, :only => [:show]
  # GET /nutrition_infos
  # GET /nutrition_infos.json
  def index
    @nutrition_infos = NutritionInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nutrition_infos }
    end
  end

  # GET /nutrition_infos/1
  # GET /nutrition_infos/1.json
  def show
    @nutrition_info = NutritionInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nutrition_info }
    end
  end

  # GET /nutrition_infos/new
  # GET /nutrition_infos/new.json
  def new
    @nutrition_info = NutritionInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nutrition_info }
    end
  end

  # GET /nutrition_infos/1/edit
  def edit
    @nutrition_info = NutritionInfo.find(params[:id])
  end

  # POST /nutrition_infos
  # POST /nutrition_infos.json
  def create
    @nutrition_info = NutritionInfo.new(params[:nutrition_info])

    respond_to do |format|
      if @nutrition_info.save
        format.html { redirect_to @nutrition_info, notice: 'Nutrition info was successfully created.' }
        format.json { render json: @nutrition_info, status: :created, location: @nutrition_info }
      else
        format.html { render action: "new" }
        format.json { render json: @nutrition_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nutrition_infos/1
  # PUT /nutrition_infos/1.json
  def update
    @nutrition_info = NutritionInfo.find(params[:id])

    respond_to do |format|
      if @nutrition_info.update_attributes(params[:nutrition_info])
        format.html { redirect_to @nutrition_info, notice: 'Nutrition info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nutrition_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nutrition_infos/1
  # DELETE /nutrition_infos/1.json
  def destroy
    @nutrition_info = NutritionInfo.find(params[:id])
    @nutrition_info.destroy

    respond_to do |format|
      format.html { redirect_to nutrition_infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nutrition_infos_helper.rb
module NutritionInfosHelper
end

app/views/nutrition_infos/_form.html.erb
<%= form_for(@nutrition_info) do |f| %>
  <% if @nutrition_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nutrition_info.errors.count, "error") %> prohibited this nutrition_info from being saved:</h2>

      <ul>
      <% @nutrition_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :calories %><br />
    <%= f.text_field :calories %>
  </div>
  <div class="field">
    <%= f.label :protein %><br />
    <%= f.text_field :protein %>
  </div>
  <div class="field">
    <%= f.label :fat %><br />
    <%= f.text_field :fat %>
  </div>
  <div class="field">
    <%= f.label :carbohydates %><br />
    <%= f.text_field :carbohydates %>
  </div>
  <div class="field">
    <%= f.label :fiber %><br />
    <%= f.text_field :fiber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nutrition_infos/edit.html.erb
<h1>Editing nutrition_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @nutrition_info %> |
<%= link_to 'Back', nutrition_infos_path %>

app/views/nutrition_infos/index.html.erb
<h1>Listing nutrition_infos</h1>

<table>
  <tr>
    <th>Recipe</th>
    <th>Calories</th>
    <th>Protein</th>
    <th>Fat</th>
    <th>Carbohydates</th>
    <th>Fiber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nutrition_infos.each do |nutrition_info| %>
  <tr>
    <td><%= nutrition_info.recipe_id %></td>
    <td><%= nutrition_info.calories %></td>
    <td><%= nutrition_info.protein %></td>
    <td><%= nutrition_info.fat %></td>
    <td><%= nutrition_info.carbohydates %></td>
    <td><%= nutrition_info.fiber %></td>
    <td><%= link_to 'Show', nutrition_info %></td>
    <td><%= link_to 'Edit', edit_nutrition_info_path(nutrition_info) %></td>
    <td><%= link_to 'Destroy', nutrition_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nutrition info', new_nutrition_info_path %>

app/views/nutrition_infos/new.html.erb
<h1>New nutrition_info</h1>

<%= render 'form' %>

<%= link_to 'Back', nutrition_infos_path %>

app/views/nutrition_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Recipe:</b>
  <%= @nutrition_info.recipe_id %>
</p>

<p>
  <b>Calories:</b>
  <%= @nutrition_info.calories %>
</p>

<p>
  <b>Protein:</b>
  <%= @nutrition_info.protein %>
</p>

<p>
  <b>Fat:</b>
  <%= @nutrition_info.fat %>
</p>

<p>
  <b>Carbohydates:</b>
  <%= @nutrition_info.carbohydates %>
</p>

<p>
  <b>Fiber:</b>
  <%= @nutrition_info.fiber %>
</p>


<%= link_to 'Edit', edit_nutrition_info_path(@nutrition_info) %> |
<%= link_to 'Back', nutrition_infos_path %>